--PK 및 외래키 삭제 후 테이블 삭제
ALTER TABLE HR.MYMUSIC DROP CONSTRAINT FK_MUSIC;

ALTER TABLE HR."rank" DROP CONSTRAINT FK_MUSIC2;

ALTER TABLE HR.GEN DROP CONSTRAINT FK_MUSIC3;

ALTER TABLE HR.MUSIC DROP CONSTRAINT MUSIC_PK;

DROP TABLE HR.MUSIC

DROP TABLE HR.GEN

DROP TABLE HR."rank"

DROP TABLE HR.MYMUSIC 

CREATE TABLE "HR"."MUSIC"
(	"ID" NUMBER(38,0),
"TITLE" VARCHAR2(100),
"ARTIST" VARCHAR2(100),
"IMG" NUMBER(38,0),
CONSTRAINT "MUSIC_PK" PRIMARY KEY ("ID"));

CREATE TABLE "HR"."USER"
(	"ID" VARCHAR2(100),
"PW" VARCHAR2(100),
"NAME" VARCHAR2(100),
CONSTRAINT "USER_PK" PRIMARY KEY ("ID"));

CREATE TABLE "HR"."MYMUSIC"
(	"MUSIC_ID" NUMBER(38,0),
"USER_ID" VARCHAR2(100),
"HEART" VARCHAR2(100),
"BUY" VARCHAR2(100)
)

ALTER TABLE HR.MYMUSIC ADD CONSTRAINT FK_MUSIC FOREIGN KEY (MUSIC_ID) REFERENCES HR.MUSIC(ID);

ALTER TABLE HR.MYMUSIC ADD CONSTRAINT FK_USER FOREIGN KEY (USER_ID) REFERENCES HR."USER"(ID);